changelog:
  exclude:
    authors:
      - 'dependabot'  # 過濾機器人 PR
    files:
      - '.github/workflows/**'  # ✅ 也排除 GitHub Actions 變更
      - '.github/changelog.yml'
  categories:
    - title: '🚀 New Features'
      labels:
        - 'type: feature'

    - title: '🐛 Bug Fixes'
      labels:
        - 'type: bug(fix)'

    - title: '📖 Documentation'
      labels:
        - 'type: docs'

    - title: '🔨 Refactor'
      labels:
        - 'type: refactor'

    - title: '🛠 Other Changes'
      labels:
        - '*'
