name: Commit Message Labeler (for push)

on:
  push:
    branches:
      - main  # ✅ 讓 Push 也能標籤

jobs:
  label-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read last commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

      - name: Determine labels based on commit message
        run: |
          if [[ "${{ env.COMMIT_MSG }}" =~ ^feat: ]]; then
            echo "Detected feature commit, adding label."
            gh issue create --title "Feature commit detected" --body "Commit message: ${{ env.COMMIT_MSG }}" --label "type: feature"
          elif [[ "${{ env.COMMIT_MSG }}" =~ ^fix: ]]; then
            echo "Detected bug fix, adding label."
            gh issue create --title "Bug fix detected" --body "Commit message: ${{ env.COMMIT_MSG }}" --label "type: bug(fix)"
          elif [[ "${{ env.COMMIT_MSG }}" =~ ^docs: ]]; then
            echo "Detected documentation update, adding label."
            gh issue create --title "Docs update detected" --body "Commit message: ${{ env.COMMIT_MSG }}" --label "type: docs"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
